<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Josefin Oleryd">

<title>Analys av försäkringskostnader</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="analysis_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analysis_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analysis_files/libs/bootstrap/bootstrap-0df8dfdce555b5e457e6102d33c50900.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analys av försäkringskostnader</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Josefin Oleryd </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="inledning" class="level2">
<h2 class="anchored" data-anchor-id="inledning">Inledning</h2>
<p>Jag, en analytiker på det påhittade försäkringsbolaget Villkor i Finstil, har fått i uppdrag att</p>
<ul>
<li><p>identifiera vilka faktorer som driver försäkringskostnader</p></li>
<li><p>utvärdera om nuvarande prissättning följer rimliga mönster</p></li>
<li><p>undersöka om en regressionsmodell kan användas som stöd vid framtida prissättning</p></li>
</ul>
</section>
<section id="dataförståelse" class="level2">
<h2 class="anchored" data-anchor-id="dataförståelse">Dataförståelse</h2>
<section id="ladda-in-data" class="level3">
<h3 class="anchored" data-anchor-id="ladda-in-data">Ladda in data</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/insurance_costs.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="storlek-struktur-och-variabeltyper" class="level3">
<h3 class="anchored" data-anchor-id="storlek-struktur-och-variabeltyper">Storlek, struktur och variabeltyper</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,100
Columns: 14
$ customer_id       &lt;chr&gt; "C100000", "C100001", "C100002", "C100003", "C100004…
$ age               &lt;dbl&gt; 48, 40, 50, 62, 39, 39, 63, 52, 36, 49, 36, 36, 45, …
$ sex               &lt;chr&gt; "female", "male", "female", "male", "female", "femal…
$ region            &lt;chr&gt; "east", "west", "south", "north", "east", "west", "e…
$ bmi               &lt;dbl&gt; 24.8, 29.5, 18.3, 25.5, 27.3, 23.3, 23.9, 24.8, 28.6…
$ children          &lt;dbl&gt; 0, 1, 2, 5, 2, 4, 3, 2, 0, 2, 2, 2, 1, 1, 1, 1, 0, 3…
$ smoker            &lt;chr&gt; "no", "no", "no", "yes", "no", "no", "no", "no", "no…
$ chronic_condition &lt;chr&gt; "no", "no", "no", "no", "no", "no", "no", "no", "yes…
$ exercise_level    &lt;chr&gt; "high", "medium", "high", "medium", "medium", "high"…
$ plan_type         &lt;chr&gt; "basic", "basic", "standard", "basic", "basic", "sta…
$ prior_accidents   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0…
$ prior_claims      &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 3, 0, 0, 0…
$ annual_checkups   &lt;dbl&gt; 1, 4, 3, NA, 0, 2, 1, 2, 3, 2, 3, 3, 4, 4, 2, 1, 2, …
$ charges           &lt;dbl&gt; 6439.10, 8274.06, 5190.99, 14500.35, 6534.40, 8026.3…</code></pre>
</div>
</div>
<p>Datasetet består av 1100 rader (observationer) och 14 kolumner.</p>
<p>En rad är en kund.</p>
<p>Kategoriska variabler:</p>
<ul>
<li><p>customer_id</p></li>
<li><p>sex</p></li>
<li><p>region</p></li>
<li><p>smoker</p></li>
<li><p>chronic_condition</p></li>
<li><p>exercise_level</p></li>
<li><p>plan_type</p></li>
</ul>
<p>Numeriska variabler:</p>
<ul>
<li><p>age</p></li>
<li><p>bmi</p></li>
<li><p>children</p></li>
<li><p>prior_accidents</p></li>
<li><p>prior_claims</p></li>
<li><p>annual_checkups</p></li>
<li><p>charges</p></li>
</ul>
</section>
<section id="dubbletter" class="level3">
<h3 class="anchored" data-anchor-id="dubbletter">Dubbletter</h3>
<section id="identiska-rader" class="level4">
<h4 class="anchored" data-anchor-id="identiska-rader">Identiska rader</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data_raw <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">duplicated</span>() <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>duplicated() kollar vilka rader som är dubbletter och returnerar en logisk lista med TRUE och FALSE. sum() summerar alla värden i listan, men då TRUE = 1 och FALSE = 0 så är det antalet TRUE som blir resultatet. I det här fallet är antalet identiska rader 0.</p>
</section>
<section id="förekommer-samma-kund-flera-gånger" class="level4">
<h4 class="anchored" data-anchor-id="förekommer-samma-kund-flera-gånger">Förekommer samma kund flera gånger?</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data_raw <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(customer_id) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 2
# ℹ 2 variables: customer_id &lt;chr&gt;, n &lt;int&gt;</code></pre>
</div>
</div>
<p>count() räknar varje customer_id och lägger resultatet i en tabell med kolumnerna customer_id och n (antal). filter(n &gt; 1) tar sedan fram de rader där n är större än 1. Resultatet är en tibble med 0 rader, dvs samma customer_id finns inte med fler än en gång.</p>
</section>
<section id="samma-kunddata-men-olika-idn" class="level4">
<h4 class="anchored" data-anchor-id="samma-kunddata-men-olika-idn">Samma kunddata, men olika id:n</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data_raw <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>customer_id) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">duplicated</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Här används duplicated() igen för att kolla vilka rader som är dubbletter, men customer_id är borträknat. Även här är resultatet en tom lista.</p>
<p>Jag undersökte dubblerad data på tre sätt:</p>
<ol type="1">
<li><p>Identiska rader</p></li>
<li><p>Samma kund på flera ställen</p></li>
<li><p>Samma kund med olika id:n</p></li>
</ol>
<p>Dubbletter gör datan skev och inte lika tillförlitlig. Identiska rader är lätta att hantera: en av raderna tas bort. Om samma kund finns på flera ställen, antingen med samma id och olika data eller med exakt samma data fast olika id:n tyder detta på inkonsekvenser vid datalagringen. Detta går inte hantera utan att först kolla med den som äger systemet som datan kommer ifrån. Har en ny kund av misstag fått ett upptaget id? Har en gammal kund av misstag skapats igen? Eller är det mot all förmodan så att två separata individer har exakt samma värden i samtliga variabler? Detta kan ägaren till systemet svara på, men går det inte att få något svar får all duplicering tas bort.</p>
<p>Som tur är innehåller detta dataset inga dubbletter.</p>
</section>
</section>
<section id="saknade-värden" class="level3">
<h3 class="anchored" data-anchor-id="saknade-värden">Saknade värden</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>data_raw <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)))) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">andel =</span> value <span class="sc">/</span> <span class="fu">nrow</span>(data_raw) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(andel))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 3
   name              value andel
   &lt;chr&gt;             &lt;int&gt; &lt;dbl&gt;
 1 bmi                  28  2.55
 2 exercise_level       22  2   
 3 annual_checkups      20  1.82
 4 customer_id           0  0   
 5 age                   0  0   
 6 sex                   0  0   
 7 region                0  0   
 8 children              0  0   
 9 smoker                0  0   
10 chronic_condition     0  0   
11 plan_type             0  0   
12 prior_accidents       0  0   
13 prior_claims          0  0   
14 charges               0  0   </code></pre>
</div>
</div>
<p>summarise() skapar en sammanfattning av datasetet och resultatet blir en ny, mindre tabell.</p>
<p>across() betyder “gör samma sak över flera kolumner” och det som ska göras är sum(is.na()), alltså summera alla NA.</p>
<p>everything() gör så att funktionen körs på alla kolumner. Punkten i na(.) är en placeholder för varje kolumn.</p>
<p>pivot_longer() gör om tabellen från “bred” till “lång”. Utan pivot_longer() blir tabellen ungefär så här:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>customer_id</td>
<td>bmi</td>
<td>age</td>
<td>prior_claims</td>
</tr>
<tr class="even">
<td>0</td>
<td>3</td>
<td>0</td>
<td>2</td>
</tr>
</tbody>
</table>
<p>Men med pivot_longer() blir tabellen ännu mer sammanfattande:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>name</td>
<td>value</td>
</tr>
<tr class="even">
<td>customer_id</td>
<td>0</td>
</tr>
<tr class="odd">
<td>bmi</td>
<td>3</td>
</tr>
<tr class="even">
<td>age</td>
<td>0</td>
</tr>
<tr class="odd">
<td>prior_claims</td>
<td>2</td>
</tr>
</tbody>
</table>
<p>Dvs att varje “orginalkolumn” hamnar i en ny kolumn “name” och antalet NA per kolumn hamnar i den nya kolumnen “value”.</p>
<p>mutate() skapar ytterligare en kolumn “andel” som beräknar andelen NA per variabel.</p>
<p>arrange() sorterar tabellen så variabeln med högst andel saknade värden ligger överst.</p>
<p>Resultatet blir som sagt en ny tabell och i det här fallet kan vi se att det finns NA i tre variabler: bmi, exercise_level och annual_checkups med totalt 70 NA. Dessa behöver hanteras i nästa del: Dataförberedelse.</p>
<section id="finns-det-observationer-med-fler-än-en-na" class="level4">
<h4 class="anchored" data-anchor-id="finns-det-observationer-med-fler-än-en-na">Finns det observationer med fler än en NA?</h4>
<p>Men är det 70 separata observationer som har NA:s eller finns det observationer som har NA i fler än en variabel?</p>
<p>Det här är relevant att veta inför hanteringen av NA. Om man väljer att ta bort alla rader med NA är det 70 observationer som försvinner eller bara 5?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_upset</span>(data_raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s1-fler-NA-per-observation-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>gg_miss_upset() är en funktion från paketet naniar. Det den gör är i princip samma sak som ovan - räknar saknade värden per kolumn och summerar - men gg_miss_upset() hittar också kombinationer av NA:s som förekommer tillsammans och ritar alltihopa i en snygg plot.</p>
<p>Av figuren kan vi utläsa att endast en observation har fler än en NA och att de är i variablerna bmi och exercise_level som dessa sakande värden förekommer.</p>
<p>Detta innebär att om NA:s hanteras genom radering så kommer 69 observationer försvinna.</p>
</section>
</section>
<section id="inkonsekvenser" class="level3">
<h3 class="anchored" data-anchor-id="inkonsekvenser">Inkonsekvenser</h3>
<section id="kategoriska-variabler" class="level4">
<h4 class="anchored" data-anchor-id="kategoriska-variabler">Kategoriska variabler</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>data_raw <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.character), <span class="sc">-</span>customer_id) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(name, value) <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">kategorier =</span> <span class="fu">paste</span>(value, <span class="at">collapse =</span> <span class="st">", "</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  name              kategorier                                 
  &lt;chr&gt;             &lt;chr&gt;                                      
1 chronic_condition no, yes                                    
2 exercise_level    high, medium, low, NA                      
3 plan_type         basic, standard, premium, Premium, Standard
4 region            east, west, south, north, North, South     
5 sex               female, male                               
6 smoker            no, yes, Yes                               </code></pre>
</div>
</div>
<p>select(where(is.character), -customer_id) väljer alla kategoriska variabler förutom customer_id (för den är inte av intresse)</p>
<p>distinct() plockar ut alla unika värden ur både name (variabel) och value (kategorier inom variablerna). group_by() slår sedan ihop dem per kolumn.</p>
<p>summarise() skapar en sammanfattande kolumn - “kategorier” - där alla värden i value slås ihop till en enda textsträng, där varje value separeras av ett kommatecken.</p>
<p>Inkonsekvenser i kategoriska variabler är exempelvis olika stavningar för samma sak, eller att ett ord ibland börjar med stor bokstav och ibland med liten bokstav. I tabellen framgår det att dessa inkonsekvenser finns i datasetet och detta kommer hanteras i avsnittet “Datastädning”.</p>
</section>
<section id="numeriska-variabler" class="level4">
<h4 class="anchored" data-anchor-id="numeriska-variabler">Numeriska variabler</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data_raw <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age             bmi           children     prior_accidents 
 Min.   :18.00   Min.   :17.00   Min.   :0.000   Min.   :0.0000  
 1st Qu.:34.00   1st Qu.:24.30   1st Qu.:0.000   1st Qu.:0.0000  
 Median :42.50   Median :27.50   Median :1.000   Median :0.0000  
 Mean   :42.51   Mean   :27.43   Mean   :1.575   Mean   :0.2382  
 3rd Qu.:51.00   3rd Qu.:30.60   3rd Qu.:3.000   3rd Qu.:0.0000  
 Max.   :75.00   Max.   :44.00   Max.   :5.000   Max.   :3.0000  
                 NA's   :28                                      
  prior_claims    annual_checkups    charges     
 Min.   :0.0000   Min.   :0.00    Min.   : 1204  
 1st Qu.:0.0000   1st Qu.:1.00    1st Qu.: 6837  
 Median :0.0000   Median :2.00    Median : 9124  
 Mean   :0.2718   Mean   :2.09    Mean   :10060  
 3rd Qu.:0.0000   3rd Qu.:3.00    3rd Qu.:12710  
 Max.   :3.0000   Max.   :4.00    Max.   :32559  
                  NA's   :20                     </code></pre>
</div>
</div>
<p>För att få fram inkonsekvenser i de numeriska variablerna väljer jag att göra en summary() på data_raw, men bara på “is.numeric”.</p>
<p>Inkonsekvenser i numeriska variabler är exempelvis negativa tal på ställen där det inte är realistiskt möjlig, som exempelvis age, bmi eller annual_checkups. Orimligt höga värden är också inkonsekvenser. Än så länge finns det ingen människa äldre än 120 år eller som har ett bmi på över 180 (#JonBrowerMinnoch #Murica) så där hade jag fått dra gränsen.</p>
<p>Men den främsta användningen av summary() är att kolla datans fördelning, skevhet och outliers.</p>
<ul>
<li><p>Charges:</p>
<ul>
<li><p>Medelvärdet högre än medianen. Tyder på högerskev fördelning.</p></li>
<li><p>Maxvärdet är mer än 2,5 gånger större än 3:e kvartilen. Tyder på outliers i den övre delen av spektrat.</p></li>
</ul></li>
<li><p>BMI:</p>
<ul>
<li><p>Medelvärdet och medianen är nästan exakt lika stora. Tyder på normalfördelning.</p></li>
<li><p>1:a kvartilen börjar på 24,30 vilket innebär att 75 % av populationen ligger i kategorin övervikt eller fetma (BMI &gt; 25)</p></li>
</ul></li>
<li><p>Age:</p>
<ul>
<li><p>Medelvärdet och medianen är nästan identiska. Tyder på normalfördelning.</p></li>
<li><p>Avståndet mellan kvartilerna är relativt konstant vilket innebär en jämn spridning mellan åldrarna</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="fördelning" class="level3">
<h3 class="anchored" data-anchor-id="fördelning">Fördelning</h3>
<section id="kategoriska-variabler-1" class="level4">
<h4 class="anchored" data-anchor-id="kategoriska-variabler-1">Kategoriska variabler</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>data_raw <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.character), <span class="sc">-</span>customer_id) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(name, value) <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">andel =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n), <span class="at">.by_group =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="cn">Inf</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 22 × 4
# Groups:   name [6]
   name              value        n  andel
   &lt;chr&gt;             &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;
 1 chronic_condition no         832 75.6  
 2 chronic_condition yes        268 24.4  
 3 exercise_level    medium     561 51    
 4 exercise_level    low        307 27.9  
 5 exercise_level    high       210 19.1  
 6 exercise_level    &lt;NA&gt;        22  2    
 7 plan_type         standard   549 49.9  
 8 plan_type         basic      339 30.8  
 9 plan_type         premium    201 18.3  
10 plan_type         Premium      7  0.636
11 plan_type         Standard     4  0.364
12 region            south      315 28.6  
13 region            west       264 24    
14 region            north      255 23.2  
15 region            east       253 23    
16 region            North        8  0.727
17 region            South        5  0.455
18 sex               female     551 50.1  
19 sex               male       549 49.9  
20 smoker            no         896 81.5  
21 smoker            yes        200 18.2  
22 smoker            Yes          4  0.364</code></pre>
</div>
</div>
<p>Inför analys är det alltid viktigt att veta hur stora de olika grupperna är.</p>
<p>I den här tabellen kan vi exempelvis se att ungefär 25 % av populationen har ett kroniskt tillstånd och att fördelningen mellan män och kvinnor är jämn.</p>
</section>
<section id="numeriska-variabler-1" class="level4">
<h4 class="anchored" data-anchor-id="numeriska-variabler-1">Numeriska variabler</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>hist_plot_eda <span class="ot">&lt;-</span> data_raw <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, bmi, charges) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Fördelning av age, bmi och charges"</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Värde"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Antal"</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Här gör pivot_longer(everything()) att ggplot() kan rita alla tre variabler samtidigt. Alla värden från bmi, age och charges ligger i value.</p>
<p>facet_wrap() skapar en separat graf för varje variabel i name.</p>
<p>scales = “free” gör att varje graf får egna axelskalor vilket är ett måste eftersom charges innehåller så mycket större värden jämfört med age och bmi.</p>
<p>theme_minimal() ger graferna ett enklare och renare utseende.</p>
<p>element_text(hjust = 0.5) centrerar rubriken.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>hist_plot_eda</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s1-visa-histogram-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Figuren bekräftar det vi misstänkte tidigare:</p>
<ul>
<li><p>Charges är högerskev med en tydlig svans av outliers vid höga värden.</p></li>
<li><p>BMI följer en normalfördelning</p></li>
</ul>
<p>Men Age har en mer oregelbunden fördelning med flera toppar, en vid 35-40 och en vid 45-50 år. Detta tyder på en ojämn representation av åldersgrupper i datan.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>box_plot_eda <span class="ot">&lt;-</span> data_raw <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, bmi, charges) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> value)) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Boxplots för age, bmi och charges"</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Värde"</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>()</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>På samma sätt som med histogrammet plottas en facetterad boxplot.</p>
<p>Då x-axeln inte är av intresse tas denna bort med axis.text.x = blank och axis.ticks.x = blank.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>box_plot_eda</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s1-visa-boxplot-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Figuren bekräftar att det finns flertalet outliers inom Charges. Många runt 25 000, men även en över 30 000. Boxploten bekräftar också att fördelningen är högerskev. Detta ser vi då boxen ligger långt ner i förhållande till maxvärdet.</p>
<p>För BMI syns nu tydligt att det finns några outliers i det övre spannet, men för övrigt är fördeningen inom BMI symmetrisk.</p>
<p>Age har inga outliers och boxen är stor och centralt placerad vilket visar på bra spridning av observationer i åldrarna 35-50 år.</p>
</section>
</section>
</section>
<section id="datastädning-och-förberedelse" class="level2">
<h2 class="anchored" data-anchor-id="datastädning-och-förberedelse">Datastädning och förberedelse</h2>
<section id="funktion-för-att-få-typvärdet-mode" class="level3">
<h3 class="anchored" data-anchor-id="funktion-för-att-få-typvärdet-mode">Funktion för att få typvärdet (mode)</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>get_mode <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  ux <span class="ot">&lt;-</span> <span class="fu">unique</span>(<span class="fu">na.omit</span>(x))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  ux[<span class="fu">which.max</span>(<span class="fu">tabulate</span>(<span class="fu">match</span>(x, ux)))]</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I föregående avsnitt upptäckte vi att exercise_level innehöll 22 NA:n och att 22 observationer motsvarar 2 % av hela datan. Vi kunde också se att exercise_level bestod av 3 kategorier: low, medium och high med en rimlig fördelning inom kategorierna (low = 307, medium = 561 och high = 210 observationer).</p>
<p>Eftersom datasetet redan är litet är jag motvillig att ta bort något. Eftersom kategorin medium redan var så stor valde jag att ersätta alla saknade värden i exercise_level med det vanligaste, medium. Men för att göra koden säker inför framtiden då datan kan ändras skapade jag en funktion som tar fram det vanligaste värdet (mode) istället för att hårdkoda.</p>
</section>
<section id="städa-och-feature-engineering-i-samma-pipe" class="level3">
<h3 class="anchored" data-anchor-id="städa-och-feature-engineering-i-samma-pipe">Städa och feature engineering i samma pipe</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>data_clean <span class="ot">&lt;-</span> data_raw <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Standardisera text</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">where</span>(is.character), <span class="sc">~</span><span class="fu">str_to_lower</span>(<span class="fu">str_trim</span>(.))),</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Hantera saknade värden</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">bmi =</span> <span class="fu">if_else</span>(</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(bmi),</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">median</span>(bmi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>      bmi),</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">annual_checkups =</span> <span class="fu">if_else</span>(</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(annual_checkups),</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">median</span>(annual_checkups, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>      annual_checkups),</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">exercise_level =</span> <span class="fu">if_else</span>(</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(exercise_level),</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">get_mode</span>(exercise_level),</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>      exercise_level),</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Logiska variabler för beräkningar</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoker_logic =</span> <span class="fu">recode</span>(smoker, <span class="st">"yes"</span> <span class="ot">=</span> <span class="cn">TRUE</span>, <span class="st">"no"</span> <span class="ot">=</span> <span class="cn">FALSE</span>),</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">chronic_condition_logic =</span> <span class="fu">recode</span>(chronic_condition, <span class="st">"yes"</span> <span class="ot">=</span> <span class="cn">TRUE</span>, <span class="st">"no"</span> <span class="ot">=</span> <span class="cn">FALSE</span>),</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Nya variabler</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">bmi_category =</span> <span class="fu">case_when</span>(</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>      bmi <span class="sc">&lt;</span> <span class="fl">18.5</span> <span class="sc">~</span> <span class="st">"underweight"</span>,</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>      bmi <span class="sc">&lt;</span> <span class="fl">25.0</span> <span class="sc">~</span> <span class="st">"normal"</span>,</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>      bmi <span class="sc">&lt;</span> <span class="fl">30.0</span> <span class="sc">~</span> <span class="st">"overweight"</span>,</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"obese"</span></span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_category =</span> <span class="fu">case_when</span>(</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>      age <span class="sc">&lt;</span> <span class="dv">35</span> <span class="sc">~</span> <span class="st">"young"</span>,</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>      age <span class="sc">&lt;</span> <span class="dv">55</span> <span class="sc">~</span> <span class="st">"middle-aged"</span>,</span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"senior"</span></span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">prior_events =</span> prior_accidents <span class="sc">+</span> prior_claims,</span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">risk_score =</span> </span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.integer</span>(smoker_logic) <span class="sc">+</span></span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.integer</span>(chronic_condition_logic) <span class="sc">+</span></span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>      <span class="fu">if_else</span>(bmi <span class="sc">&gt;=</span> <span class="dv">30</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Kategoriska variabler till faktorer</span></span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoker =</span> <span class="fu">factor</span>(smoker_logic, <span class="at">levels =</span> <span class="fu">c</span>(<span class="cn">FALSE</span>, <span class="cn">TRUE</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"no"</span>, <span class="st">"yes"</span>)),</span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">chronic_condition =</span> <span class="fu">factor</span>(chronic_condition_logic, <span class="at">levels =</span> <span class="fu">c</span>(<span class="cn">FALSE</span>, <span class="cn">TRUE</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"no"</span>, <span class="st">"yes"</span>)),</span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">region =</span> <span class="fu">as.factor</span>(region),</span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">exercise_level =</span> <span class="fu">factor</span>(exercise_level, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"medium"</span>, <span class="st">"high"</span>)),</span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">plan_type =</span> <span class="fu">factor</span>(plan_type, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"basic"</span>, <span class="st">"standard"</span>, <span class="st">"premium"</span>)),</span>
<span id="cb24-49"><a href="#cb24-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">as.factor</span>(sex),</span>
<span id="cb24-50"><a href="#cb24-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">bmi_category =</span> <span class="fu">factor</span>(bmi_category, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"underweight"</span>, <span class="st">"normal"</span>, <span class="st">"overweight"</span>, <span class="st">"obese"</span>)),</span>
<span id="cb24-51"><a href="#cb24-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_category =</span> <span class="fu">factor</span>(age_category, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"young"</span>, <span class="st">"middle-aged"</span>, <span class="st">"senior"</span>))</span>
<span id="cb24-52"><a href="#cb24-52" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb24-53"><a href="#cb24-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>smoker_logic, <span class="sc">-</span>chronic_condition_logic)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Följande städning görs (med utgångspunkt i det som tidigare avsnitt visade):</p>
<ul>
<li><p>Alla kategoriska variabler standardiseras, dvs alla mellanslag tas bort och alla bokstäver görs om till gemener</p></li>
<li><p>Saknade värden i bmi och annual_checkups ersätts med medianvärdet då detta inte “skjuter” datan åt ett specifikt håll. exercise_level NA:ns ersätts som sagt med det vanligaste värdet mha av funktionen get_mode.</p></li>
</ul>
<p>Skapande av nya variabler, val och motivering:</p>
<ul>
<li><p>bmi_category och age_category</p>
<ul>
<li><p>kategorier ger minskat brus och fångar tröskeleffekter: slumpmässiga variationer mellan exempelvis en 66-åring och 68-åring eller mellan ett bmi på 21 och ett bmi på 23 försvinner när observationerna grupperas, och ger istället en tydligare struktur som är lättare att tolka.</p></li>
<li><p>bmi_category följer WHO:s etablerade standarder</p></li>
</ul></li>
<li><p>prior_events</p>
<ul>
<li><p>prior_accidents och prior_claims säger egentligen samma sak (“saker som gör att kunden kostar pengar”), och om variabler korrelerar för mycket med varandra kan det störa vissa statistiska modeller</p></li>
<li><p>dessa enskilda variabler innehöll rätt mycket gles data (många 0) och att kombinera dem ger då en variabel med mer variation (mer signal) som gör det lättare för modeller att hitta mönster</p></li>
</ul></li>
<li><p>risk_score</p>
<ul>
<li><p>både rökning, högt bmi och kroniskt tillstånd är risker så precis som med prior_accidents och prior_claims bör dessa hanteras tillsammans och inte var för sig</p></li>
<li><p>risk_score ger en bra gruppering av observationerna som är lätt att använda i försäkringssammanhang</p></li>
</ul></li>
</ul>
<p>risk_score skapas genom att smoker, chronic_condition och bmi vardera kan ge 1 poäng:</p>
<ul>
<li><p>smoker_yes = 1 poäng (annars 0)</p></li>
<li><p>chronic_condition_yes = 1 poäng (annars 0)</p></li>
<li><p>bmi över 30 = 1 poäng (annars 0)</p></li>
</ul>
<p>Kategoriska variabler –&gt; faktorer</p>
<p>Alla de kateogriska variablerna i datasetet (+ de nyskapade variablerna age_category och bmi_category) kan användas för att gruppera datan på olika sätt. Därför valde jag att göra dem till faktorer för att förenkla både presentationen samt användningen av dem i regressionsanalysen. En faktor går att rangordna med “levels” och då blir det automatiskt vad som är “normalläget” och vad som är “ökningen” (dvs vad händer med kostnaden om en person går från normalläget normal weight till overweight?).</p>
<p>Kategorierna hamnar även i korrekt ordning i grafer och tabeller, istället för default bokstavsordning.</p>
<p>Men för att smoker och chronic_condition ska kunna användas för att skapa risk_score behövde de först göras om till logiska variabler så att yes/TRUE = 1 och no/FALSE = 0.</p>
<p>Alla kategoriska variabler görs därför om till faktorer först i slutet av pipen.</p>
</section>
<section id="kontroll-att-det-blev-som-det-skulle-när-jag-gjorde-som-jag-gjorde" class="level3">
<h3 class="anchored" data-anchor-id="kontroll-att-det-blev-som-det-skulle-när-jag-gjorde-som-jag-gjorde">Kontroll att det blev som det skulle när jag gjorde som jag gjorde</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,100
Columns: 18
$ customer_id       &lt;chr&gt; "c100000", "c100001", "c100002", "c100003", "c100004…
$ age               &lt;dbl&gt; 48, 40, 50, 62, 39, 39, 63, 52, 36, 49, 36, 36, 45, …
$ sex               &lt;fct&gt; female, male, female, male, female, female, female, …
$ region            &lt;fct&gt; east, west, south, north, east, west, east, north, e…
$ bmi               &lt;dbl&gt; 24.8, 29.5, 18.3, 25.5, 27.3, 23.3, 23.9, 24.8, 28.6…
$ children          &lt;dbl&gt; 0, 1, 2, 5, 2, 4, 3, 2, 0, 2, 2, 2, 1, 1, 1, 1, 0, 3…
$ smoker            &lt;fct&gt; no, no, no, yes, no, no, no, no, no, yes, no, no, no…
$ chronic_condition &lt;fct&gt; no, no, no, no, no, no, no, no, yes, no, no, yes, no…
$ exercise_level    &lt;fct&gt; high, medium, high, medium, medium, high, high, medi…
$ plan_type         &lt;fct&gt; basic, basic, standard, basic, basic, standard, basi…
$ prior_accidents   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0…
$ prior_claims      &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 3, 0, 0, 0…
$ annual_checkups   &lt;dbl&gt; 1, 4, 3, 2, 0, 2, 1, 2, 3, 2, 3, 3, 4, 4, 2, 1, 2, 1…
$ charges           &lt;dbl&gt; 6439.10, 8274.06, 5190.99, 14500.35, 6534.40, 8026.3…
$ bmi_category      &lt;fct&gt; normal, overweight, underweight, overweight, overwei…
$ age_category      &lt;fct&gt; middle-aged, middle-aged, middle-aged, senior, middl…
$ prior_events      &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 1, 3, 0, 0, 0…
$ risk_score        &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>data_clean <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age             bmi           children     prior_accidents 
 Min.   :18.00   Min.   :17.00   Min.   :0.000   Min.   :0.0000  
 1st Qu.:34.00   1st Qu.:24.40   1st Qu.:0.000   1st Qu.:0.0000  
 Median :42.50   Median :27.50   Median :1.000   Median :0.0000  
 Mean   :42.51   Mean   :27.43   Mean   :1.575   Mean   :0.2382  
 3rd Qu.:51.00   3rd Qu.:30.50   3rd Qu.:3.000   3rd Qu.:0.0000  
 Max.   :75.00   Max.   :44.00   Max.   :5.000   Max.   :3.0000  
  prior_claims    annual_checkups    charges       prior_events 
 Min.   :0.0000   Min.   :0.000   Min.   : 1204   Min.   :0.00  
 1st Qu.:0.0000   1st Qu.:1.000   1st Qu.: 6837   1st Qu.:0.00  
 Median :0.0000   Median :2.000   Median : 9124   Median :0.00  
 Mean   :0.2718   Mean   :2.088   Mean   :10060   Mean   :0.51  
 3rd Qu.:0.0000   3rd Qu.:3.000   3rd Qu.:12710   3rd Qu.:1.00  
 Max.   :3.0000   Max.   :4.000   Max.   :32559   Max.   :5.00  
   risk_score    
 Min.   :0.0000  
 1st Qu.:0.0000  
 Median :1.0000  
 Mean   :0.7064  
 3rd Qu.:1.0000  
 Max.   :3.0000  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>data_clean <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.factor)) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     sex        region    smoker    chronic_condition exercise_level
 female:551   east :253   no :896   no :832           low   :307    
 male  :549   north:263   yes:204   yes:268           medium:583    
              south:320                               high  :210    
              west :264                                             
    plan_type        bmi_category      age_category
 basic   :339   underweight: 32   young      :286  
 standard:553   normal     :285   middle-aged:631  
 premium :208   overweight :478   senior     :183  
                obese      :305                    </code></pre>
</div>
</div>
<p>Ser snyggt ut!</p>
</section>
</section>
<section id="beskrivande-analys" class="level2">
<h2 class="anchored" data-anchor-id="beskrivande-analys">Beskrivande analys</h2>
<section id="korrelationsmatris" class="level3">
<h3 class="anchored" data-anchor-id="korrelationsmatris">Korrelationsmatris</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>corr_plot <span class="ot">&lt;-</span> data_clean <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, bmi, prior_accidents, prior_claims, annual_checkups, prior_events, risk_score, charges) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggcorrplot</span>(<span class="at">type =</span> <span class="st">"upper"</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">lab =</span> <span class="cn">TRUE</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">lab_size =</span> <span class="dv">3</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">colors =</span> <span class="fu">c</span>(<span class="st">"#E4672E"</span>, <span class="st">"white"</span>, <span class="st">"#6D9EC1"</span>),</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">title =</span> <span class="st">"Korrelation mellan variabler och försäkringskostnad (charges)"</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">ggtheme =</span> <span class="fu">theme_minimal</span>()) <span class="sc">+</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>cor() skapar en korrelationsmatris över de numeriska variabler valda i steget innan (select()).</p>
<p>Sedan används funktionen ggcorrplot() från paketet ggcorrplot för att enkelt plotta korrelationsmatrisen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>corr_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s3-visa-korrelationsmatris-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Jag valde att börja den beskrivande analysen med en korrelationsmatris som är ett snabbt och enkelt sätt att få en överblick över linjära samband inför regressionsanalysen.</p>
<p>Korrelationsmatrisen blev ett bra bevis på att det var en god idé att skapa variabeln risk_score och att behålla den som en numerisk variabel. Som numerisk variabel kan den vara med i en korrelationsmatris!</p>
<p>charges och risk_score har en stark korrelation (0.69) medan endast bmi ger en låg korrelation (0.15) vilket är ett gott tecken på att även smoker och chronic_condition är intressanta i en regressionsanalys. Att bmi och risk_score har en medelhög korrelation (0.44) tyder på att bmi har sin förtjänade plats i risk_score.</p>
<p>charges och age har en måttlig korrelation (0.26), men som tredje “bästa” korrelation är age också en intressant variabel.</p>
<p>Korrelationsmatrisen visar också att det var en bra idé att slå ihop prior_claims och prior_accidents då prior_events har en högre korrelation (0.27) jämfört med claims och accidents separat (0.18 resp. 0.24).</p>
<p>annual_checkups har mycket låg korrelation och är därför inte av intresse.</p>
</section>
<section id="hälsorisker-och-livsstil" class="level3">
<h3 class="anchored" data-anchor-id="hälsorisker-och-livsstil">Hälsorisker och livsstil</h3>
<p>För att se hur kostnaden ser ut inom grupperna, men också mellan grupperna, väljer jag att slå två flugor i en smäll och visuallisera detta med boxplots.</p>
<p>Med hjälp av korrelationsmatrisen har jag kommit fram till att de intressanta variablerna är:</p>
<ul>
<li><p>risk_score</p></li>
<li><p>smoker</p></li>
<li><p>chronic_condition</p></li>
<li><p>bmi_category</p></li>
<li><p>age_category</p></li>
<li><p>prior_events</p></li>
</ul>
<p>Dessa variabler delar naturligt upp observationerna i lämpliga grupper (förutom prior_events, såklart, som är numerisk) och jag väljer att dela upp dem i två kategorier:</p>
<ol type="1">
<li><p>Hälsorisker och livsstil: risk_score, smoker, chronic_condition och bmi_category</p></li>
<li><p>Demografiska grupper: age_category och här får även sex vara med</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>health_risk_plot <span class="ot">&lt;-</span> data_clean <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(charges, smoker, chronic_condition, bmi_category, risk_score) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span>charges, as.character)) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>charges, <span class="at">names_to =</span> <span class="st">"variable"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">value =</span> <span class="fu">factor</span>(value, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"no"</span>, <span class="st">"yes"</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"underweight"</span>, <span class="st">"normal"</span>, <span class="st">"overweight"</span>, <span class="st">"obese"</span>,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"0"</span>, <span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  ))) <span class="sc">%&gt;%</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">outlier.alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>variable, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span> </span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)) <span class="sc">+</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Kostnadsskillnader baserat på hälso- och riskfaktorer"</span>,</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Kategori"</span>,</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kostnad (charges)"</span></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>mutate(across(-charges, as.character)) ändrar alla variabler förutom charges till text (charges förblir numeric eftersom charges kommer ligga på y-axeln). Varför? För att jag använder pivot_longer() som behöver ha alla variabler i samma format. Varför pivot_longer? För att det ska gå enkelt att plotta flera små boxplots i samma figur.</p>
<p>När variablerna görs om till character försvinner “inställningarna” de fick när jag i script 02 gjorde om dem till faktorer. Så för att alla kategorier ska hamna i korrekt ordning igen behövs mutate(value = factor()) osv.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>health_risk_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s3-visa-health_risk_plot-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<section id="bmi_category" class="level4">
<h4 class="anchored" data-anchor-id="bmi_category">bmi_category</h4>
<ul>
<li>skillnaden mellan underweight och normal är relativt liten, lika så mellan overweight och obese. Dock har obese en högre median samt fler outliers.</li>
</ul>
</section>
<section id="chronic_condition" class="level4">
<h4 class="anchored" data-anchor-id="chronic_condition">chronic_condition</h4>
<ul>
<li>individer med kroniska tillstånd har mycket högre mediankostnad. Nästan hela boxen ligger förskjuten ovanför “no”, vilket innebär att även de “billigaste” fallen med kroniska tillstånd ofta kostar mer än genomsnitten för dem utan.</li>
</ul>
</section>
<section id="risk_score" class="level4">
<h4 class="anchored" data-anchor-id="risk_score">risk_score</h4>
<ul>
<li>för varje steg i risk_score hoppar mediankostnaden kraftigt uppåt. Grupp 3 har en kompakt och högt placerad box, vilket tyder på att högt risk_score ger nästan uteslutande höga kostnader med liten variation.</li>
</ul>
</section>
<section id="smoker" class="level4">
<h4 class="anchored" data-anchor-id="smoker">smoker</h4>
<ul>
<li>rökare har betydligt högre mediankostnad än icke-rökare. Gruppen icke-rökare har dock många outliers i det övre spannet vilket tyder på att även om rökning ger högre kostnader, så finns det andra faktorer som driver upp kostnaden för icke-rökare.</li>
</ul>
</section>
</section>
<section id="demografiska-grupper" class="level3">
<h3 class="anchored" data-anchor-id="demografiska-grupper">Demografiska grupper</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>demographic_plot <span class="ot">&lt;-</span> data_clean <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(charges, age_category, sex) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span>charges, as.character)) <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>charges, <span class="at">names_to =</span> <span class="st">"variable"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">value =</span> <span class="fu">factor</span>(value, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"young"</span>, <span class="st">"middle-aged"</span>, <span class="st">"senior"</span>,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"male"</span>, <span class="st">"female"</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  ))) <span class="sc">%&gt;%</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">outlier.alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>variable, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span> </span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)) <span class="sc">+</span></span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Kostnadsskillnader baserat på ålder och kön"</span>,</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Kategori"</span>,</span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kostnad (charges)"</span></span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>demographic_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s3-visa-demographic_plot-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<section id="age_category" class="level4">
<h4 class="anchored" data-anchor-id="age_category">age_category</h4>
<ul>
<li>tydlig uppåtgående trend där mediankostnaden stiger linjärt från young till senior. Boxen för senior är större (större interkvartilavstånd) än boxarna för både young och middle-age, vilket betyder att kostnaderna för seniorer varierar mer från person till person. Både gruppen young och gruppen middle-age har många fler outliers än seniorerna och detta pekar på att andra faktorer än åldern driver upp kostnaderna.</li>
</ul>
</section>
<section id="sex" class="level4">
<h4 class="anchored" data-anchor-id="sex">sex</h4>
<ul>
<li>skillnaden är minimal mellan män och kvinnor (hurra för jämställdhet!). Medianerna ligger nästan på samma nivå, det är nästan samma spridning inom de båda grupperna och de ser ut att ha lika många outliers, även om spridningen på extremvärdena ser olika ut mellan grupperna.</li>
</ul>
</section>
</section>
<section id="genomsnittlig-kostnad-per-risk-score" class="level3">
<h3 class="anchored" data-anchor-id="genomsnittlig-kostnad-per-risk-score">Genomsnittlig kostnad per Risk Score</h3>
<p>Jag rundar av den beskrivande analysen med att undersöka de faktiska kostnaderna för varje risk_score-grupp genom att rita ett stapeldiagram över medel- och mediankostnad.</p>
<p>Visar diagrammet på ett linjärt förhållande (dvs att det är jämna och fina hopp mellan varje risk_score) bekräftar det mitt val att behålla risk_score som numerisk. risk_score = numerisk medför att varje +1 steg är värt lika mycket och ett stapeldiagram över medelvärdet visar hur stor skillanden är varje +1 steg.</p>
<p>Om diagrammet inte visar på ett linjärt förhållande utan medelvärdet snarare sticker i höjden för risk_score 3 innebär detta att jag bör fundera på att göra om risk_score till en faktor innan regressionsanalysen. Detta för att fånga upp det icke-linjära sambandet mellan riskgrupperna.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Skapa sammanfattande tabell</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>risk_score_summary <span class="ot">&lt;-</span> data_clean <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(risk_score) <span class="sc">%&gt;%</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Antal =</span> <span class="fu">n</span>(),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    Medelvärde <span class="ot">=</span> <span class="fu">mean</span>(charges),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median =</span> <span class="fu">median</span>(charges)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(risk_score_summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  risk_score Antal Medelvärde Median
       &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;  &lt;dbl&gt;
1          0   492      7271.  7236.
2          1   446     10777. 10558.
3          2   155     16230. 16832.
4          3     7     23850. 24718.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotta i stapeldiagram</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>risk_summary_plot <span class="ot">&lt;-</span> risk_score_summary <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(Medelvärde, Median),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"Statistiktyp"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"Kostnad"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(risk_score), <span class="at">y =</span> Kostnad, <span class="at">fill =</span> Statistiktyp)) <span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(Kostnad, <span class="dv">0</span>)),</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>),</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>) <span class="sc">+</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Medelvärde"</span> <span class="ot">=</span> <span class="st">"lightblue"</span>, <span class="st">"Median"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>)) <span class="sc">+</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Jämförelse av medelvärde och median per risk score"</span>,</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Risk score (0-3)"</span>,</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kostnad (charges)"</span>,</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Mått"</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Även här används pivot_longer() för att ggplot() lättare ska kunna plotta det jag vill (två staplar per riskgrupp).</p>
<p>x = factor(risk_score) betyder att x-axeln ska visa risk_score som kategorier (vilket annars gör det svårt för ggplot() att få staplarna snygga bredvid varandra).</p>
<p>fill = Statistiktyp: färgen på staplarna bestäms av om det är medelvärde eller median.</p>
<p>geom_col() används när det finns färdiga y-värden (dvs “Kostnad”).</p>
<p>position = “dodge” gör att staplarna hamnar bredvid och inte på varandra.</p>
<p>geom_text() lägger till texten ovanpå staplarna.</p>
<p>scale_fill_manual() används för att bestämma vilken färg det ska vara på staplarna (dvs vilken färg får medelvärdet resp. medianvärdet?)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>risk_summary_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s3-visa-risk_summary_plot-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Diagrammet visar tillräckligt mycket på ett linjärt samband för att jag ska kunna försvara mitt val att behålla risk_score som numerisk. Även om man kan ana en liten extra ökning på slutet mellan Risk 2 och Risk 3. Dock inte tillräckligt för att få mig att ändra mig.</p>
<p>Medelvärde och median ligger nära varandra inom varje grupp vilket tyder på att kostnaderna inte verkar vara extremt snedfördelade inom grupperna.</p>
<p>Riskgrupp 1 (och även riskgrupp 0, marginellt) har ett något högre medelvärde jämfört med medianvärde vilket innebär att några individer i den här gruppen drar upp snittet. Vilket i sin tur kan innebära att risk_score ensamt inte förklarar charges.</p>
<p>På samma sätt innebär ett högre medianvärde jämfört med medelvärde (dvs att några individer drar ner snittet) i grupp 2 och 3 att risk_score inte förklarar alla kostnadsskillnader.</p>
</section>
</section>
<section id="regressionsanalys" class="level2">
<h2 class="anchored" data-anchor-id="regressionsanalys">Regressionsanalys</h2>
<section id="försmak-scatterplots-kontinuerliga-variabler" class="level3">
<h3 class="anchored" data-anchor-id="försmak-scatterplots-kontinuerliga-variabler">Försmak: scatterplots kontinuerliga variabler</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>scatter_age <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data_clean, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">shape =</span> <span class="dv">21</span>, </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"steelblue"</span>, </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Samband mellan ålder och försäkringskostnad"</span>,</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Ålder"</span>,</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kostnad (charges)"</span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>scatter_age</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s4-visa-plotten-age-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>scatter_bmi <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data_clean, <span class="fu">aes</span>(<span class="at">x =</span> bmi, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">shape =</span> <span class="dv">21</span>, </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Samband mellan BMI och försäkringskostnad"</span>,</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"BMI"</span>,</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kostnad (charges)"</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>scatter_bmi</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s4-visa-plotten-bmi-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Som en extra kontroll innan jag kickar igång regressionsanalysen väljer jag att plotta age och bmi i scatterplots. Detta gör det möjligt att bedöma om antagandet om linjärt samband är rimligt inför regressionsanalysen.</p>
</section>
<section id="regressionsmodeller" class="level3">
<h3 class="anchored" data-anchor-id="regressionsmodeller">Regressionsmodeller</h3>
<section id="enkel-regressionsmodell-modell-1" class="level4">
<h4 class="anchored" data-anchor-id="enkel-regressionsmodell-modell-1">Enkel regressionsmodell, modell 1</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>model_baseline <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> risk_score, <span class="at">data =</span> data_clean)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_baseline)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ risk_score, data = data_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-9569.1 -2310.8    17.6  2135.8 16875.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   6990.0      139.3   50.20   &lt;2e-16 ***
risk_score    4346.8      137.5   31.62   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3311 on 1098 degrees of freedom
Multiple R-squared:  0.4767,    Adjusted R-squared:  0.4762 
F-statistic:  1000 on 1 and 1098 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Scatterplotsen indikerar att varken age eller bmi ensamma uppvisar ett starkt linjärt samband med charges, vilket tyder på att ytterligare variabler behöver inkluderas för att förklara variationen. Tidigare analyser visar att risk_score har en starkare koppling till charges, varför regressionsanalysen inleds med en modell där denna variabel inkluderas som central förklarande faktor.</p>
<p>Att börja med en enkel modell är en etablerad strategi då det ger en tydlig referenspunkt och underlättar tolkningen av hur ytterligare variabler påverkar modellen.</p>
<p>En sammanfattning av modellens resultat visar:</p>
<ul>
<li><p>Intercept (6990): “grundkostnaden” dvs en person med risk_score 0 förväntas ha en kostnad på 6990 enheter</p></li>
<li><p>Risk_score (4346.8): kostnaden ökar med 4346.8 enheter för varje steg risk_score ökar</p></li>
<li><p>P-värdet är mycket lågt och har fått tre stjärnor vilket innebär att sambandet mellan risk_score och charges är statistiskt säkerställt</p></li>
<li><p>Förklaringsgraden (R2) är 0.4767 - risk_score förklarar ensamt nästan 48 % av all variation i kostnaderna. Resterande 52 % förklaras av andra faktorer</p></li>
<li><p>Medianen för residualerna är nära noll, men maxvärdet är 16 875 och minvärdet är -9 569 vilket innebär att modellen missar med stora belopp. Modellens genomsnittliga felmarginal är 3311 enheter.</p></li>
</ul>
</section>
<section id="multipel-regressionsmodell-modell-2" class="level4">
<h4 class="anchored" data-anchor-id="multipel-regressionsmodell-modell-2">Multipel regressionsmodell, modell 2</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>model_multi <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> prior_events <span class="sc">+</span> risk_score, <span class="at">data =</span> data_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_multi)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ prior_events + risk_score, data = data_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-8925.4 -2250.6    55.1  2068.4 17647.8 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    6474.7      143.3  45.186   &lt;2e-16 ***
prior_events   1188.3      120.1   9.893   &lt;2e-16 ***
risk_score     4218.4      132.4  31.860   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3174 on 1097 degrees of freedom
Multiple R-squared:  0.5195,    Adjusted R-squared:  0.5187 
F-statistic: 593.1 on 2 and 1097 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Nästa naturliga steg är att skapa en multipel regressionsmodell där den självklara tillkommande variabeln är prior_events (eftersom den variabeln hade nästhögst korrelation).</p>
<p>En sammanfattning av modellens resultat visar:</p>
<ul>
<li><p>Intercept (6474.7): en person med 0 risk_score och 0 prior_events förväntas ha en kostnad på 6474.7 enheter.</p></li>
<li><p>Prior_events (1188.3): för varje tidigare händelse ökar kostnaden med ca 1188 enheter.</p></li>
<li><p>Risk_score (4218.4): kostnaden ökar med 4218.4 för varje steg risk_score ökar</p></li>
<li><p>P-värdet är mycket lågt även i den här modellen</p></li>
<li><p>Förklaringsgraden ökar med ca 4 procentenheter till 52 % jämfört med den enkla modellen</p></li>
<li><p>Residualfördelningen liknar den i baselinemodellen med en genomsnittlig felmarginal på 3174 enheter.</p></li>
</ul>
</section>
<section id="multipel-regressionsmodell---orginalvariabler-istället-för-risk_score-modell-3" class="level4">
<h4 class="anchored" data-anchor-id="multipel-regressionsmodell---orginalvariabler-istället-för-risk_score-modell-3">Multipel regressionsmodell - orginalvariabler istället för risk_score, modell 3</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ändra referensnivå för BMI-kategori till "normal"</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>data_clean<span class="sc">$</span>bmi_category <span class="ot">&lt;-</span> <span class="fu">relevel</span>(data_clean<span class="sc">$</span>bmi_category, <span class="at">ref =</span> <span class="st">"normal"</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>model_without_risk_score <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> prior_events <span class="sc">+</span> smoker <span class="sc">+</span> bmi_category <span class="sc">+</span> chronic_condition, <span class="at">data =</span> data_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Jag behöver ändra den ordning som bmi-kategorierna kommer i för att referensnivån ska vara “normal” och inte “underweight” (som jag hade när jag bara ville presentera grupperna i snygg storleksordning)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_without_risk_score)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ prior_events + smoker + bmi_category + 
    chronic_condition, data = data_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-9386.8 -1729.1  -149.6  1591.6 16971.9 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              6249.95     169.61  36.849  &lt; 2e-16 ***
prior_events             1047.06      98.41  10.640  &lt; 2e-16 ***
smokeryes                7626.90     202.52  37.660  &lt; 2e-16 ***
bmi_categoryunderweight  -250.83     485.20  -0.517 0.605287    
bmi_categoryoverweight    681.55     193.94   3.514 0.000459 ***
bmi_categoryobese        2057.93     213.36   9.645  &lt; 2e-16 ***
chronic_conditionyes     4115.23     183.46  22.432  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2588 on 1093 degrees of freedom
Multiple R-squared:  0.6817,    Adjusted R-squared:  0.6799 
F-statistic: 390.1 on 6 and 1093 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Som nästa steg ville jag testa om risk_score är så himlans bra som den vill få oss att tro. Därför valde jag att ersätta risk_score med de ingående beståndsdelarna: smoker, bmi_category och chronic_condition.</p>
<p>En sammanfattning av modellens resultat visar:</p>
<ul>
<li><p>Förklaringsgraden stiger enda upp till 68.17 %! Att ge varje hälsofaktor (smoker, bmi_category, chronic_condition) sin egen vikt gör att modellen kan förklara över 68 % av alla kostnadsskillnader</p></li>
<li><p>Modellen är mer träffsäker - residual standard error har sjunkt till 2 588, men modellen missar fortfarande med stora belopp (16 972 vs -9 387).</p></li>
<li><p>Alla faktorer förutom bmi_categoryunderweight är statistiskt signifikanta. Det betyder att det inte finns någon statistisk skillnad i kostnad mellan “underweight” och “normal”</p></li>
<li><p>Den kraftigaste faktorn är smokeryes med en koefficient på 7 626.90 - dvs att allt annat lika så är kostnaden 7 626.90 enheter högre för en rökare jämfört med en icke-rökare</p></li>
<li><p>Den näst starkaste faktorn efter rökning är chronic_conditionyes. Att ha ett kroniskt tillstånd ökar den förväntade kostnaden med ca 4 115 enheter.</p></li>
<li><p>Jämfört med “overweight” är det “obese” som driver kostnaden uppåt (2 057.93 jämfört med 681.55)</p></li>
</ul>
</section>
<section id="multipel-regressionsmodell---alla-intressanta-variabler-modell-4" class="level4">
<h4 class="anchored" data-anchor-id="multipel-regressionsmodell---alla-intressanta-variabler-modell-4">Multipel regressionsmodell - alla intressanta variabler, modell 4</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>model_extreme <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age_category <span class="sc">+</span> smoker <span class="sc">+</span> bmi_category <span class="sc">+</span> chronic_condition <span class="sc">+</span> prior_events, <span class="at">data =</span> data_clean)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_extreme)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age_category + smoker + bmi_category + 
    chronic_condition + prior_events, data = data_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-9292.3 -1639.3  -140.7  1575.7 17637.4 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              5337.40     196.11  27.216  &lt; 2e-16 ***
age_categorymiddle-aged  1010.73     176.75   5.718 1.39e-08 ***
age_categorysenior       2671.89     234.05  11.416  &lt; 2e-16 ***
smokeryes                7618.89     191.69  39.747  &lt; 2e-16 ***
bmi_categoryunderweight    36.76     459.92   0.080 0.936309    
bmi_categoryoverweight    648.79     183.51   3.536 0.000424 ***
bmi_categoryobese        1965.62     202.59   9.702  &lt; 2e-16 ***
chronic_conditionyes     3963.38     174.19  22.754  &lt; 2e-16 ***
prior_events              965.10      93.40  10.333  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2448 on 1091 degrees of freedom
Multiple R-squared:  0.7157,    Adjusted R-squared:  0.7136 
F-statistic: 343.3 on 8 and 1091 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Som sista modell valde jag att slänga in age_category också för att se vad som händer med förklaringsgraden då jag använder alla intressanta variabler.</p>
<p>Resultatet blev ingen större ökning eller skillnad jämfört med modellen innan. Förklaringsgraden ökar endast några procentenheter upp till 71.5. Rökning och kroniskt tillstånd kvarstår som de mest betydande faktorerna.</p>
</section>
</section>
<section id="sammanfattning-och-fördjupande-utvärdering" class="level3">
<h3 class="anchored" data-anchor-id="sammanfattning-och-fördjupande-utvärdering">Sammanfattning och fördjupande utvärdering</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Skapa en snygg jämförande tabell</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co"># "Layout inställningar"</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>gof_template <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"raw"</span> <span class="ot">=</span> <span class="st">"nobs"</span>, <span class="st">"clean"</span> <span class="ot">=</span> <span class="st">"Antal obs."</span>, <span class="st">"fmt"</span> <span class="ot">=</span> <span class="dv">0</span>),</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"raw"</span> <span class="ot">=</span> <span class="st">"r.squared"</span>, <span class="st">"clean"</span> <span class="ot">=</span> <span class="st">"R2"</span>, <span class="st">"fmt"</span> <span class="ot">=</span> <span class="dv">3</span>),</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"raw"</span> <span class="ot">=</span> <span class="st">"adj.r.squared"</span>, <span class="st">"clean"</span> <span class="ot">=</span> <span class="st">"R2 just."</span>, <span class="st">"fmt"</span> <span class="ot">=</span> <span class="dv">3</span>),</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"raw"</span> <span class="ot">=</span> <span class="st">"aic"</span>, <span class="st">"clean"</span> <span class="ot">=</span> <span class="st">"AIC"</span>, <span class="st">"fmt"</span> <span class="ot">=</span> <span class="dv">2</span>),</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"raw"</span> <span class="ot">=</span> <span class="st">"bic"</span>, <span class="st">"clean"</span> <span class="ot">=</span> <span class="st">"BIC"</span>, <span class="st">"fmt"</span> <span class="ot">=</span> <span class="dv">2</span>),</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"raw"</span> <span class="ot">=</span> <span class="st">"rmse"</span>, <span class="st">"clean"</span> <span class="ot">=</span> <span class="st">"Resid. std. fel"</span>, <span class="st">"fmt"</span> <span class="ot">=</span> <span class="dv">2</span>),</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"raw"</span> <span class="ot">=</span> <span class="st">"statistic"</span>, <span class="st">"clean"</span> <span class="ot">=</span> <span class="st">"F-statistik"</span>, <span class="st">"fmt"</span> <span class="ot">=</span> <span class="dv">1</span>),</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"raw"</span> <span class="ot">=</span> <span class="st">"p.value"</span>, <span class="st">"clean"</span> <span class="ot">=</span> <span class="st">"F (p-värde)"</span>, <span class="st">"fmt"</span> <span class="ot">=</span> <span class="dv">3</span>)</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Lista över modellerna</span></span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Modell 1: Baseline"</span> <span class="ot">=</span> model_baseline,</span>
<span id="cb55-20"><a href="#cb55-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Modell 2: Multipel"</span> <span class="ot">=</span> model_multi,</span>
<span id="cb55-21"><a href="#cb55-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Modell 3: Orginalvariabler istället för risk_score"</span> <span class="ot">=</span> model_without_risk_score,</span>
<span id="cb55-22"><a href="#cb55-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Modell 4: Alla intressanta variabler"</span> <span class="ot">=</span> model_extreme</span>
<span id="cb55-23"><a href="#cb55-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-24"><a href="#cb55-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-25"><a href="#cb55-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabellen</span></span>
<span id="cb55-26"><a href="#cb55-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-27"><a href="#cb55-27" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(models,</span>
<span id="cb55-28"><a href="#cb55-28" aria-hidden="true" tabindex="-1"></a>             <span class="at">output =</span> <span class="st">"output/regression/summary_table.png"</span>,</span>
<span id="cb55-29"><a href="#cb55-29" aria-hidden="true" tabindex="-1"></a>             <span class="at">fmt =</span> <span class="dv">2</span>,</span>
<span id="cb55-30"><a href="#cb55-30" aria-hidden="true" tabindex="-1"></a>             <span class="at">stars =</span> <span class="cn">TRUE</span>,</span>
<span id="cb55-31"><a href="#cb55-31" aria-hidden="true" tabindex="-1"></a>             <span class="at">gof_map =</span> gof_template,</span>
<span id="cb55-32"><a href="#cb55-32" aria-hidden="true" tabindex="-1"></a>             <span class="at">title =</span> <span class="st">"Jämförelse: Från enkel till komplex modell"</span>)</span>
<span id="cb55-33"><a href="#cb55-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-34"><a href="#cb55-34" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"output/regression/summary_table.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="output/regression/summary_table.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Jag väljer att göra en sammanfattande tabell med hjälp av funktionen modelsummary() från paketet modelsummary och lägger till måtten AIC (Akaike Information Criterion) och BIC (Bayesian Information Criterion) för att se om modellerna faktiskt blir bättre av fler variabler.</p>
<p>R2 stiger nästan alltid när man lägger till fler variabler i en modell, men det betyder inte automatiskt att modellen är bättre (pga overfitting). AIC och BIC är mått som straffar modellen om den är onödigt komplex. När det kommer till AIC och BIC är lägre värden bättre. Anledningen att AIC/BIC är uppe på över 20 000 är pga skalan på datan (dvs att charges är höga siffror och att antalet observationer är över 1 000).</p>
<p>I tabellen går det att utläsa att mellan modell 1 och modell 4 sjunker både AIC och BIC (som är strängare) från 20 956/20 971 till 20 299/20 349 vilket är ett statistiskt bevis på att de nya variablerna faktiskt tillför värde.</p>
<section id="fördjupande-utvärdering" class="level4">
<h4 class="anchored" data-anchor-id="fördjupande-utvärdering">Fördjupande utvärdering</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>pred_resid_data <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  data_clean <span class="sc">%&gt;%</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">predicted =</span> <span class="fu">predict</span>(model_multi),</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">residual =</span> charges <span class="sc">-</span> predicted,</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">model =</span> <span class="st">"Modell 2: Multipel"</span>),</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  data_clean <span class="sc">%&gt;%</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">predicted =</span> <span class="fu">predict</span>(model_extreme),</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">residual =</span> charges <span class="sc">-</span> predicted,</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">model =</span> <span class="st">"Modell 4: Max"</span>)</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>För att förstå varför och när en modell har fel valde jag att göra 3 figurer:</p>
<ul>
<li><p>residualanalys</p></li>
<li><p>faktiskt vs predikterat pris</p></li>
<li><p>normalfördelningen av fel (qq-plot)</p></li>
</ul>
<p>Och för att se om felen blir färre och mindre när modellen blir bättre valde jag att jämföra Modell 2 (den “enkla” multipla modellen) och Modell 4 (den “extrema” multipla modellen).</p>
<p>För att åstadkomma detta behövde jag samla faktiska värden, förutsagda värden och felmarginaler i en enda tabell: pred_resid_data.</p>
<p>bind_rows() är en funktion som tar två (eller fler) dataset och lägger dem “på varandra” (vertikalt).</p>
<p>Den första delen av bind_rows() tar data_clean och kör den igenom en mutate-funktion. I mutate() skapas tre nya kolumner för den första modellen:</p>
<ul>
<li><p>predicted: predict() räknar ut vad modellen tror att värdet ska vara för varje rad</p></li>
<li><p>residual: felet räknas ut med formeln “charges” - “predicted”</p></li>
<li><p>model: en etikett (“Modell 2: Multipel”) läggs till så varje rad tillhör en modell</p></li>
</ul>
<p>Sedan görs samma sak för den andra modellen.</p>
<p>När bind_rows() är klar har man fått en lång tabell där övre hälften innehåller all orginaldata plus beräkningar från den första modellen och där den nedre häften innehåller samma orginaldata fast med beräkningar från den andra modellen.</p>
<p>Det här objektet, pred_resid_data, används sedan med ggplot() för att skapa figurerna.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>plot_resid_pred <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pred_resid_data, <span class="fu">aes</span>(<span class="at">x =</span> predicted, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> model, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residualanalys"</span>,</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Modellens gissning (Predicted)"</span>,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Felmarginal (Residual)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>plot_resid_pred</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s4-visa-resid-pred-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Här vill man se prickarna slumpmässigt utspridda kring noll-linjen.</p>
<p>Att båda modellerna har ser ut att ha ungefär lika många prickar över linjen som under linjen är i grunden bra. Det betyder att modellerna inte bara gissar för högt eller för lågt hela tiden.</p>
<p>Men spridningen är ganska stor, det finns många punkter långt från noll. Modellerna fångar en del av kostnadsvariationerna, men absolut inte allt. Det finns mycket kvar som modellerna inte förklarar.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>plot_actual_charge <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pred_resid_data, <span class="fu">aes</span>(<span class="at">x =</span> predicted, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span> </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> model) <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Faktiskt vs Predikterat pris"</span>,</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Modellens gissning (Predicted)"</span>,</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Faktiskt kostnad (Actual)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>plot_actual_charge</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s4-visa-acutal-charge-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Den röda streckade linjen motsvarar “perfektion” dvs predicted = faktiskt kostnad.</p>
<p>Molnet för modell 4 följer linjen någorlunda och har inte de där “banden” (prickarna bildar lodräta streck) som modell 2 har. Sådana band uppstår då modellen har få variabler och delar in observationerna i fåtal fack och ger alla i det facket samma gissning. Modell 4 har fler variabler som hjälper till att förklara kostnadsvariationerna och blir därför mer nyanserad.</p>
<p>Båda modellerna har extremvärden som springer iväg långt ifrån linjen, framförallt långt över. Det innebär att modellerna missar de dyrare fallen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>plot_qq <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pred_resid_data, <span class="fu">aes</span>(<span class="at">sample =</span> residual)) <span class="sc">+</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> model) <span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"QQ-plot: normalfördelning av fel"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>plot_qq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/s4-visa-qq-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>För att en linjär regression ska vara pålitligt vill vi att felen ska vara normalfördelade, punkterna ska alltså följa den röda linjen.</p>
<p>I mitten ser det riktigt snyggt ut! De flesta fel följer linjen klockrent. Men i ändarna går det utför… (eller uppför). Modellerna har liknande “heavy tails” vilket betyder att de underskattar de dyraste fallen. Modellerna har alltså svårt med extremer, framförallt höga, men också låga i mindre utsträckning.</p>
</section>
</section>
</section>
<section id="tolkning-och-slutsatser" class="level2">
<h2 class="anchored" data-anchor-id="tolkning-och-slutsatser">Tolkning och slutsatser</h2>
<p>De starkaste sambanden med kostnader identifierades både genom explorativ analys och genom regressionsmodeller. Variabler kopplade till hälsorisk, såsom rökning, kroniska tillstånd och högt bmi, visade tydlig korrelation med kostnader.</p>
<p>Analysen visar att en strukturerad datastädningsprocess har betydelse för modellernas resultat. Standardisering av kategoriska variabler samt hantering av saknade värden bidrog till att minska brus och inkonsekvenser i datan.</p>
<p>Feature engineering, såsom skapandet av risk_score och prior_events, förbättrade modellens möjlighet att fånga underliggande mönster.</p>
<p>Den bästa regressionsmodellen lyckades fånga de övergripande trenderna i datan, men hade svårare att modellera extremvärden i kostnader.</p>
<p>Trots att modellen fångar flera viktiga samband finns begränsningar. Fördelningen av kostnader är högerskev med flera outliers vilket gör att en linjär modell har svårt att prediktera höga kostnader.</p>
<p>Modellen antar också linjära samband mellan variabler och kostnader, vilket sannolikt inte fullt ut speglar verkligheten.</p>
<p>Flera förbättringar hade kunnat stärka analysen. En möjlig åtgärd är att transformera målvariabeln för att hantera skevhet och förbättra modellens prestanda. log-transform av charges är ett exempel (där stora värden hade “tryckts ihop” och därmed dämpat outliers).</p>
<p>Mer avancerade modeller, exempelvis beslutsträd eller ensemblemetoder, kunnat testas för att bättre fånga icke-linjära samband.</p>
<p>Även mer systematisk validering, train/test-split och cross-validation, kunnat ge en mer robust utvärdering av modellen,</p>
<p>Slutligen hade ytterligare feature engineering, såsom interaktionseffekter mellan variabler (t. ex. rökning och ålder) kunnat ge ytterligare förbättringar.</p>
</section>
<section id="självreflektion" class="level2">
<h2 class="anchored" data-anchor-id="självreflektion">Självreflektion</h2>
<p>Följande tycker jag att jag gjorde särskilt bra:</p>
<ul>
<li><p>Strukturerad arbetsprocess där varje steg kopplas till nästa</p></li>
<li><p>Grundlig datakvalitetsanalys, där jag tycker att min undersökning av flera olika typer av dubbletter sticker ut</p></li>
<li><p>Tydlig och ordningsam kod</p></li>
<li><p>Genomtänkt feature engineering</p></li>
<li><p>Enhetliga figurer</p></li>
</ul>
<p>Följande tyckte jag att jag gjorde mindre bra:</p>
<ul>
<li>Jag bör ha gett mig själv mer tid att “kill your darlings”. Jag känner att arbetet hade gått att göra lite mer koncist, men nu på grund av tidsbrist behöver jag behålla allt för att inte tappa den röda tråden. Anledningen att det blev så långt är att det var så kul och jag ville undersöka ALLT. Men allt behöver ju inte lämnas in (även om en viss Joakim en gång sa att “jag inte kommer hindra er från att göra MER” och jag har verkligen tagit detta till mig…)</li>
</ul>
<p>Följande tyckte jag var särskilt svårt:</p>
<ul>
<li>Det var svårt att arbeta med Quarto. Det tog en bra stund innan jag fick flyt på hur det behöver stå i scripten och i quarto-filen för att det ska renderas en snygg rapport. Jupyter Notebook är så otroligt mycket mer lättanvänd. Jag saknade det lätta flöde som Jupyter Notebook ger när man kan samla all kod och all output på samma ställe. Med scripts och Quarto var det svårt att få till strukturen.</li>
</ul>
<p>Jag tycker mitt arbete motsvarar betyg VG för att samtliga betygskrav är uppfyllda. Där Tolkning och slutsatser i denna rapport samt den separata affärsmässiga rapporten till “uppdragsgivaren” särskilt uppfyller kraven:</p>
<ul>
<li><p>“visa en säkrare och mer självständig tolkning av resultaten”</p></li>
<li><p>“föra ett välgrundat resonemang om vad modellen fångar och inte fångar”</p></li>
<li><p>“diskutera möjliga förbättringar av analysen”</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>